services:
  auth-server:
    container_name: auth-server
    build: ./auth-server
    ports:
      - "9090:9090"
    healthcheck:
      test: curl --fail http://localhost:9090/.well-known/openid-configuration || exit 1
      interval: 10s
      retries: 5
    environment:
      - SPRING_PROFILES_ACTIVE=frontend

  resource-server:
    container_name: resource-server
    build: ./resource-server
    ports:
      - "8081:8181"
    depends_on:
      auth-server:
        condition: service_healthy

  client-app:
    container_name: client-app
    build: ./client-app
    ports:
      - "8080:8080"
    depends_on:
      - auth-server
      - resource-server
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8083:80"
    depends_on:
      auth-server:
        condition: service_healthy
