spring:
  application.name: oauth2-authorization-server
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9090

server:
  port: 9090
  servlet:
    session:
      tracking-modes: cookie
  error:
    whitelabel:
      enabled: false
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.example: DEBUG
custom:
  oauth2:
    redirect-uri: https://oauth.pstmn.io/v1/callback