spring:
  application.name: oauth2-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-server:9090/oauth2/jwks
          issuer-uri: http://auth-server:9090
          audiences: resource-server
logging:
  level:
    org.springframework.security: DEBUG
server:
  port: 8181
webhook:
  secret: test-secret